// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Araponga.Tests.Api.BDD
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MidiasEmChatFeature : object, Xunit.IClassFixture<MidiasEmChatFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaInChat.feature"
#line hidden
        
        public MidiasEmChatFeature(MidiasEmChatFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Api/BDD", "Mídias em Chat", "  Como um usuário\r\n  Eu quero enviar mídias no chat\r\n  Para compartilhar imagens " +
                    "e áudios em conversas", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que existe um território \"Vale do Itamambuca\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um usuário \"João\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.AndAsync("que existe um usuário \"Maria\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que o usuário \"João\" está autenticado", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enviar imagem no chat")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Chat")]
        [Xunit.TraitAttribute("Description", "Enviar imagem no chat")]
        public async System.Threading.Tasks.Task EnviarImagemNoChat()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Enviar imagem no chat", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.GivenAsync("que existe uma imagem \"imagem1.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.WhenAsync("o usuário envia uma mensagem com a imagem \"imagem1.jpg\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("a mensagem deve ser enviada com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 17
    await testRunner.AndAsync("a mensagem deve conter a imagem", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enviar áudio no chat")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Chat")]
        [Xunit.TraitAttribute("Description", "Enviar áudio no chat")]
        public async System.Threading.Tasks.Task EnviarAudioNoChat()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Enviar áudio no chat", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("que existe um áudio \"audio1.mp3\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("o usuário envia uma mensagem com o áudio \"audio1.mp3\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("a mensagem deve ser enviada com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("a mensagem deve conter o áudio", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tentar enviar vídeo no chat (bloqueado)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Chat")]
        [Xunit.TraitAttribute("Description", "Tentar enviar vídeo no chat (bloqueado)")]
        public async System.Threading.Tasks.Task TentarEnviarVideoNoChatBloqueado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Tentar enviar vídeo no chat (bloqueado)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("que existe um vídeo \"video1.mp4\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 27
    await testRunner.WhenAsync("o usuário tenta enviar uma mensagem com o vídeo \"video1.mp4\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 28
    await testRunner.ThenAsync("deve retornar erro \"video\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enviar imagem maior que 5MB (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Chat")]
        [Xunit.TraitAttribute("Description", "Enviar imagem maior que 5MB (limite excedido)")]
        public async System.Threading.Tasks.Task EnviarImagemMaiorQue5MBLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Enviar imagem maior que 5MB (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.GivenAsync("que existe uma imagem de 6MB disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 32
    await testRunner.WhenAsync("o usuário tenta enviar uma mensagem com a imagem", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 33
    await testRunner.ThenAsync("deve retornar erro \"size exceeds\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Enviar áudio maior que 2MB (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Chat")]
        [Xunit.TraitAttribute("Description", "Enviar áudio maior que 2MB (limite excedido)")]
        public async System.Threading.Tasks.Task EnviarAudioMaiorQue2MBLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Enviar áudio maior que 2MB (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.GivenAsync("que existe um áudio de 3MB disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 37
    await testRunner.WhenAsync("o usuário tenta enviar uma mensagem com o áudio", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 38
    await testRunner.ThenAsync("deve retornar erro \"size exceeds\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MidiasEmChatFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MidiasEmChatFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
