// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Araponga.Tests.Api.BDD
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MidiasEmPostsFeature : object, Xunit.IClassFixture<MidiasEmPostsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaInPosts.feature"
#line hidden
        
        public MidiasEmPostsFeature(MidiasEmPostsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Api/BDD", "Mídias em Posts", "  Como um usuário\r\n  Eu quero adicionar mídias aos meus posts\r\n  Para enriquecer " +
                    "o conteúdo compartilhado", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que existe um território \"Vale do Itamambuca\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um usuário \"João\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.AndAsync("que o usuário \"João\" está autenticado", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar post com uma imagem")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Criar post com uma imagem")]
        public async System.Threading.Tasks.Task CriarPostComUmaImagem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar post com uma imagem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.GivenAsync("que existe uma imagem \"imagem1.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 14
    await testRunner.WhenAsync("o usuário cria um post com a imagem \"imagem1.jpg\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("o post deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("o post deve conter 1 mídia", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar post com múltiplas imagens")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Criar post com múltiplas imagens")]
        public async System.Threading.Tasks.Task CriarPostComMultiplasImagens()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar post com múltiplas imagens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("que existem 5 imagens disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 20
    await testRunner.WhenAsync("o usuário cria um post com as 5 imagens", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 21
    await testRunner.ThenAsync("o post deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 22
    await testRunner.AndAsync("o post deve conter 5 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar post com mais de 10 mídias (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Criar post com mais de 10 mídias (limite excedido)")]
        public async System.Threading.Tasks.Task CriarPostComMaisDe10MidiasLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar post com mais de 10 mídias (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("que existem 11 imagens disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.WhenAsync("o usuário tenta criar um post com as 11 imagens", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 27
    await testRunner.ThenAsync("deve retornar erro \"media items allowed\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar post com vídeo e imagem")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Criar post com vídeo e imagem")]
        public async System.Threading.Tasks.Task CriarPostComVideoEImagem()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar post com vídeo e imagem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("que existe uma imagem \"imagem1.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 31
    await testRunner.AndAsync("que existe um vídeo \"video1.mp4\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.WhenAsync("o usuário cria um post com a imagem e o vídeo", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 33
    await testRunner.ThenAsync("o post deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 34
    await testRunner.AndAsync("o post deve conter 2 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar post com mais de um vídeo (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Criar post com mais de um vídeo (limite excedido)")]
        public async System.Threading.Tasks.Task CriarPostComMaisDeUmVideoLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar post com mais de um vídeo (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.GivenAsync("que existem 2 vídeos disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 38
    await testRunner.WhenAsync("o usuário tenta criar um post com os 2 vídeos", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 39
    await testRunner.ThenAsync("deve retornar erro \"video\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar post remove mídias associadas")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Posts")]
        [Xunit.TraitAttribute("Description", "Deletar post remove mídias associadas")]
        public async System.Threading.Tasks.Task DeletarPostRemoveMidiasAssociadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Deletar post remove mídias associadas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.GivenAsync("que existe um post com 3 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 43
    await testRunner.WhenAsync("o usuário deleta o post", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 44
    await testRunner.ThenAsync("o post deve ser deletado", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 45
    await testRunner.AndAsync("as 3 mídias devem ser removidas", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MidiasEmPostsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MidiasEmPostsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
