// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Araponga.Tests.Api.BDD
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MidiasEmMarketplaceFeature : object, Xunit.IClassFixture<MidiasEmMarketplaceFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaInMarketplace.feature"
#line hidden
        
        public MidiasEmMarketplaceFeature(MidiasEmMarketplaceFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Api/BDD", "Mídias em Marketplace", "  Como um vendedor\r\n  Eu quero adicionar mídias aos meus itens\r\n  Para mostrar os" +
                    " produtos de forma atrativa", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que existe um território \"Vale do Itamambuca\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um usuário \"João\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.AndAsync("que o usuário \"João\" está autenticado", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
    await testRunner.AndAsync("que existe uma loja \"Loja do João\"", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar item com imagem principal")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Marketplace")]
        [Xunit.TraitAttribute("Description", "Criar item com imagem principal")]
        public async System.Threading.Tasks.Task CriarItemComImagemPrincipal()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar item com imagem principal", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.GivenAsync("que existe uma imagem \"produto1.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.WhenAsync("o usuário cria um item com a imagem \"produto1.jpg\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("o item deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 17
    await testRunner.AndAsync("o item deve ter uma imagem principal", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar item com múltiplas imagens")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Marketplace")]
        [Xunit.TraitAttribute("Description", "Criar item com múltiplas imagens")]
        public async System.Threading.Tasks.Task CriarItemComMultiplasImagens()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar item com múltiplas imagens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("que existem 5 imagens disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("o usuário cria um item com as 5 imagens", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("o item deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("o item deve ter 5 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 24
    await testRunner.AndAsync("a primeira imagem deve ser a imagem principal", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar item com mais de 10 mídias (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Marketplace")]
        [Xunit.TraitAttribute("Description", "Criar item com mais de 10 mídias (limite excedido)")]
        public async System.Threading.Tasks.Task CriarItemComMaisDe10MidiasLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar item com mais de 10 mídias (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("que existem 11 imagens disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.WhenAsync("o usuário tenta criar um item com as 11 imagens", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 29
    await testRunner.ThenAsync("deve retornar erro \"media items allowed\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar item com vídeo e imagens")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Marketplace")]
        [Xunit.TraitAttribute("Description", "Criar item com vídeo e imagens")]
        public async System.Threading.Tasks.Task CriarItemComVideoEImagens()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar item com vídeo e imagens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("que existe uma imagem \"produto1.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 33
    await testRunner.AndAsync("que existe um vídeo \"video1.mp4\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 34
    await testRunner.WhenAsync("o usuário cria um item com a imagem e o vídeo", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 35
    await testRunner.ThenAsync("o item deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 36
    await testRunner.AndAsync("o item deve ter 2 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 37
    await testRunner.AndAsync("a primeira mídia deve ser a imagem principal", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Arquivar item remove mídias associadas")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Marketplace")]
        [Xunit.TraitAttribute("Description", "Arquivar item remove mídias associadas")]
        public async System.Threading.Tasks.Task ArquivarItemRemoveMidiasAssociadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Arquivar item remove mídias associadas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
    await testRunner.GivenAsync("que existe um item com 3 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 41
    await testRunner.WhenAsync("o usuário arquiva o item", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 42
    await testRunner.ThenAsync("o item deve ser arquivado", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 43
    await testRunner.AndAsync("as 3 mídias devem ser removidas", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MidiasEmMarketplaceFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MidiasEmMarketplaceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
