// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Araponga.Tests.Api.BDD
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MidiasEmEventosFeature : object, Xunit.IClassFixture<MidiasEmEventosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaInEvents.feature"
#line hidden
        
        public MidiasEmEventosFeature(MidiasEmEventosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Api/BDD", "Mídias em Eventos", "  Como um organizador de eventos\r\n  Eu quero adicionar mídias aos eventos\r\n  Para" +
                    " promover e documentar eventos", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que existe um território \"Vale do Itamambuca\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um usuário \"João\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
    await testRunner.AndAsync("que o usuário \"João\" está autenticado", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar evento com imagem de capa")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Eventos")]
        [Xunit.TraitAttribute("Description", "Criar evento com imagem de capa")]
        public async System.Threading.Tasks.Task CriarEventoComImagemDeCapa()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar evento com imagem de capa", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.GivenAsync("que existe uma imagem \"capa.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 14
    await testRunner.WhenAsync("o usuário cria um evento com a imagem de capa \"capa.jpg\"", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
    await testRunner.ThenAsync("o evento deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
    await testRunner.AndAsync("o evento deve ter uma imagem de capa", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar evento com capa e mídias adicionais")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Eventos")]
        [Xunit.TraitAttribute("Description", "Criar evento com capa e mídias adicionais")]
        public async System.Threading.Tasks.Task CriarEventoComCapaEMidiasAdicionais()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar evento com capa e mídias adicionais", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("que existe uma imagem \"capa.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 20
    await testRunner.AndAsync("que existem 3 imagens adicionais disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 21
    await testRunner.WhenAsync("o usuário cria um evento com a capa e as 3 imagens adicionais", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("o evento deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("o evento deve ter 1 imagem de capa", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 24
    await testRunner.AndAsync("o evento deve ter 3 mídias adicionais", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar evento com mais de 5 mídias adicionais (limite excedido)")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Eventos")]
        [Xunit.TraitAttribute("Description", "Criar evento com mais de 5 mídias adicionais (limite excedido)")]
        public async System.Threading.Tasks.Task CriarEventoComMaisDe5MidiasAdicionaisLimiteExcedido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar evento com mais de 5 mídias adicionais (limite excedido)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("que existe uma imagem \"capa.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.AndAsync("que existem 6 imagens adicionais disponíveis", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 29
    await testRunner.WhenAsync("o usuário tenta criar um evento com a capa e as 6 imagens adicionais", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 30
    await testRunner.ThenAsync("deve retornar erro \"additional media items allowed\"", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar evento com capa e vídeo adicional")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Eventos")]
        [Xunit.TraitAttribute("Description", "Criar evento com capa e vídeo adicional")]
        public async System.Threading.Tasks.Task CriarEventoComCapaEVideoAdicional()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Criar evento com capa e vídeo adicional", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.GivenAsync("que existe uma imagem \"capa.jpg\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 34
    await testRunner.AndAsync("que existe um vídeo \"video1.mp4\" disponível", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 35
    await testRunner.WhenAsync("o usuário cria um evento com a capa e o vídeo adicional", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 36
    await testRunner.ThenAsync("o evento deve ser criado com sucesso", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 37
    await testRunner.AndAsync("o evento deve ter 1 imagem de capa", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
#line 38
    await testRunner.AndAsync("o evento deve ter 1 vídeo adicional", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar evento remove mídias associadas")]
        [Xunit.TraitAttribute("FeatureTitle", "Mídias em Eventos")]
        [Xunit.TraitAttribute("Description", "Cancelar evento remove mídias associadas")]
        public async System.Threading.Tasks.Task CancelarEventoRemoveMidiasAssociadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cancelar evento remove mídias associadas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.GivenAsync("que existe um evento com 1 capa e 3 mídias adicionais", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.WhenAsync("o usuário cancela o evento", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("o evento deve ser cancelado", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("as 4 mídias devem ser removidas", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MidiasEmEventosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MidiasEmEventosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
