// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Araponga.Tests.Application.BDD
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ValidacaoDeMidiaFeature : object, Xunit.IClassFixture<ValidacaoDeMidiaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaValidation.feature"
#line hidden
        
        public ValidacaoDeMidiaFeature(ValidacaoDeMidiaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Application/BDD", "Validação de Mídia", "  Como um sistema\r\n  Eu quero validar mídias antes de processá-las\r\n  Para garant" +
                    "ir segurança e qualidade", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que existe um território \"Vale do Itamambuca\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existe um usuário \"João\" como residente", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar tamanho de imagem dentro do limite")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar tamanho de imagem dentro do limite")]
        public async System.Threading.Tasks.Task ValidarTamanhoDeImagemDentroDoLimite()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar tamanho de imagem dentro do limite", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("que existe uma imagem de 2MB", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 13
    await testRunner.WhenAsync("o sistema valida a imagem", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 14
    await testRunner.ThenAsync("a validação deve passar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 15
    await testRunner.AndAsync("a imagem deve ser aceita", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar tamanho de imagem excedendo limite")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar tamanho de imagem excedendo limite")]
        public async System.Threading.Tasks.Task ValidarTamanhoDeImagemExcedendoLimite()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar tamanho de imagem excedendo limite", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("que existe uma imagem de 15MB", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 19
    await testRunner.WhenAsync("o sistema valida a imagem", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 20
    await testRunner.ThenAsync("a validação deve falhar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 21
    await testRunner.AndAsync("deve retornar erro de validação \"size exceeds\"", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar tipo MIME permitido")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar tipo MIME permitido")]
        public async System.Threading.Tasks.Task ValidarTipoMIMEPermitido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar tipo MIME permitido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("que existe um arquivo com tipo MIME \"image/jpeg\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.WhenAsync("o sistema valida o tipo MIME", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 26
    await testRunner.ThenAsync("a validação deve passar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 27
    await testRunner.AndAsync("o arquivo deve ser aceito", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar tipo MIME não permitido")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar tipo MIME não permitido")]
        public async System.Threading.Tasks.Task ValidarTipoMIMENaoPermitido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar tipo MIME não permitido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("que existe um arquivo com tipo MIME \"application/pdf\"", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 31
    await testRunner.WhenAsync("o sistema valida o tipo MIME", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 32
    await testRunner.ThenAsync("a validação deve falhar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 33
    await testRunner.AndAsync("deve retornar erro de validação \"not allowed\"", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar quantidade de mídias dentro do limite")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar quantidade de mídias dentro do limite")]
        public async System.Threading.Tasks.Task ValidarQuantidadeDeMidiasDentroDoLimite()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar quantidade de mídias dentro do limite", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.GivenAsync("que existem 5 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 37
    await testRunner.WhenAsync("o sistema valida a quantidade", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 38
    await testRunner.ThenAsync("a validação deve passar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 39
    await testRunner.AndAsync("as mídias devem ser aceitas", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar quantidade de mídias excedendo limite")]
        [Xunit.TraitAttribute("FeatureTitle", "Validação de Mídia")]
        [Xunit.TraitAttribute("Description", "Validar quantidade de mídias excedendo limite")]
        public async System.Threading.Tasks.Task ValidarQuantidadeDeMidiasExcedendoLimite()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Validar quantidade de mídias excedendo limite", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.GivenAsync("que existem 11 mídias", ((string)(null)), ((Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 43
    await testRunner.WhenAsync("o sistema valida a quantidade", ((string)(null)), ((Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 44
    await testRunner.ThenAsync("a validação deve falhar", ((string)(null)), ((Reqnroll.Table)(null)), "Então ");
#line hidden
#line 45
    await testRunner.AndAsync("deve retornar erro de validação \"Maximum media count exceeded\"", ((string)(null)), ((Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ValidacaoDeMidiaFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ValidacaoDeMidiaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
